
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1.analizadores.cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 25;
  public static final int PLUS = 23;
  public static final int RPAREN = 29;
  public static final int ETIQUETAS = 12;
  public static final int EJECUTAR = 10;
  public static final int LLI = 17;
  public static final int LPAREN = 28;
  public static final int CRI = 22;
  public static final int LLF = 18;
  public static final int TIPO = 6;
  public static final int PORCENTAJE = 8;
  public static final int BARRAS = 3;
  public static final int VALORES = 13;
  public static final int CRF = 21;
  public static final int COMA = 20;
  public static final int NUMBER = 30;
  public static final int EOF = 0;
  public static final int TOTAL = 15;
  public static final int DIVIDE = 26;
  public static final int DEF = 2;
  public static final int PIE = 4;
  public static final int EXTRA = 9;
  public static final int CANTIDAD = 7;
  public static final int MINUS = 24;
  public static final int error = 1;
  public static final int EJEY = 11;
  public static final int EJEX = 16;
  public static final int TEXT = 31;
  public static final int FIN = 19;
  public static final int UNIR = 14;
  public static final int TITULO = 5;
  public static final int UMINUS = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "TIPO",
  "CANTIDAD",
  "PORCENTAJE",
  "EXTRA",
  "EJECUTAR",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TOTAL",
  "EJEX",
  "LLI",
  "LLF",
  "FIN",
  "COMA",
  "CRF",
  "CRI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "TEXT"
  };
}

